# Site Settings
title: Stride Game Engine
author: Stride Team
description: Stride Game Engine
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://stride3d.net" # the base hostname & protocol for your site

# Twitter
twitter_user: stridedotnet
twitter_tweet_button: true

# Links
discord-url: https://discord.gg/f6aerfE
facebook-url: https://www.facebook.com/stride3d
github-url: https://github.com/stride3d/stride
github-discussions-url: https://github.com/stride3d/stride/discussions
open-collective-url: https://opencollective.com/stride3d
twitter-url: https://twitter.com/stridedotnet
youtube-url: https://www.youtube.com/c/Stride3D
stackexchange-url: https://gamedev.stackexchange.com/questions/tagged/stride
docs-manual-url: http://doc.stride3d.net/latest/manual/
docs-requirements-url: http://doc.stride3d.net/latest/manual/
docs-release-notes-url: http://doc.stride3d.net/latest/releasenotes/

# Disqus Comments
disqus_short_name: stride3d
disqus_show_comment_count: true

# Google Analytics
googlega: 'UA-35991323-1'

# Jekyll settings
permalink: /blog/:title/
# try to fix excerpt separator
excerpt_separator: <!--more-->
# excerpt_link: Read More...
paginate: 10
paginate_path: "/blog/page:num/"

exclude:
    - .vs
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

plugins:
  - jekyll-sitemap
  - jekyll-paginate